INSERT INTO `questions` (`question_id`, `question`) VALUES
  (NULL, 'Mida tähendab HTML?'),
  (NULL, 'Milline on suurima pealkirja HTML element?'),
  (NULL, 'Millise HTML elemendiga saab sooritada reavahet?'),
  (NULL, 'Kuidas tähistatakse listi elementi?'),
  (NULL, 'Mida tähendab CSS?'),
  (NULL, 'Kuidas rõhutada teksti(itaaliapärane)?'),
  (NULL, 'Kuidas muuta tekst paksuks?'),
  (NULL, 'Milliste märkidega alustatakse HTMLis kommentaari?'),
  (NULL, 'Millise HTMLi märgendiga määratakse lehekülje pealkiri?'),
  (NULL, 'Millist HTMLi märgendit kasutatakse klõpsatava veebilingi jaoks?'),
  (NULL, 'Kuidas alustatakse HTMLi dokumenti?'),
  (NULL, 'Kuidas sisestatakse pilti?'),
  (NULL, 'Kuidas sisestatakse videot?'),
  (NULL, 'Kuidas sisestatakse heliklippi?'),
  (NULL, 'Kuidas määrata HTML dokumendi keel?'),
  (NULL, 'Kuidas muuta HTML dokumendis paragrahvi stiili?'),
  (NULL, 'Kuidas määrata font-iks Verdana?'),
  (NULL, 'Kuidas määrata taustavärvi?'),
  (NULL, 'Kuidas joondada paragrahvi paremale?'),
  (NULL, 'Mille jaoks kasutatakse <div> märgendeid?'),
  (NULL, 'Millist järgmistest märgenditest kasutatakse mitmerealise tekstisisestuse haldamiseks?'),
  (NULL, 'Millist atribuuti kasutatakse ridade arvu tähistamiseks?'),
  (NULL, 'Kuidas teha järjestatud listi?'),
  (NULL, 'Kuidas teha järjestamata listi?'),
  (NULL, 'Milline on <img> märgendi atribuut?'),
  (NULL, 'Millist järgnevatest atribuutidest kasutatakse fonti nime täpsustamiseks?'),
  (NULL, 'Kus määratakse HTMLi koodis lehekülje pealkiri?'),
  (NULL, 'Mitu märgendit on tavalises elemendis?'),
  (NULL, 'Millist atribuuti kasutatakse, et klikitav link avaneks uues aknas?'),
  (NULL, 'Milline järgmistest HTMLi märgenditest pole kehtiv?');

INSERT INTO `answers` (`answer_id`, `answer_text`, `answer_correct`, `question_id`) VALUES
  (NULL, 'HyperText Markup Language', '1', '6'),
  (NULL, 'Hyperlinks and Text Markup Language', '0', '6'),
  (NULL, 'Home Tool Markup Language', '0', '6'),
  (NULL, '<h1>', '1', '7'),
  (NULL, '<h6>', '0', '7'),
  (NULL, '<head>', '0', '7'),
  (NULL, '<br>', '1', '8'),
  (NULL, '<lb>', '0', '8'),
  (NULL, '<break>', '0', '8'),
  (NULL, '<li>', '1', '9'),
  (NULL, '<le>', '0', '9'),
  (NULL, '<element>', '0', '9'),
  (NULL, 'Cascading Style Sheets', '1', '10'),
  (NULL, 'Computer Style Sheets', '0', '10'),
  (NULL, 'Creative Style Sheets', '0', '10'),
  (NULL, '<em>', '1', '11'),
  (NULL, '<it>', '0', '11'),
  (NULL, '<italic>', '0', '11'),
  (NULL, '<strong>',  '1', '12'),
  (NULL, '<thick>',  '0', '12'),
  (NULL, '<fat>', '0', '12'),
  (NULL, '<!--',  '1', '13'),
  (NULL, '/*',  '0', '13'),
  (NULL, '//', '0', '13'),
  (NULL, '<title>', '1', '14'),
  (NULL, '<heading>', '0', '14'),
  (NULL, '<headline>', '0', '14'),
  (NULL, '<a href="google.com">', '1', '15'),
  (NULL, '<link="google.com">', '0', '15'),
  (NULL, '<url="google.com">', '0', '15'),
  (NULL, '<!DOCTYPE html>',  '1', '16'),
  (NULL, '<html document>', '0', '16'),
  (NULL, '<DOCTYPE html>', '0', '16'),
  (NULL, '<img src="">',  '1', '17'),
  (NULL, '<picture href="">', '0', '17'),
  (NULL, '<image url="">', '0', '17'),
  (NULL, '<video src="">',  '1', '18'),
  (NULL, '<movie url="">',  '0', '18'),
  (NULL, '<film href="">', '0', '18'),
  (NULL, '<audio src="">', '1', '19'),
  (NULL, '<media href="">', '0', '19'),
  (NULL, '<sound url="">', '0', '19'),
  (NULL, '<html lang="et">', '1', '20'),
  (NULL, '<doc lang="et">', '0', '20'),
  (NULL, '<language="et">', '0', '20'),
  (NULL, '<p style="font-size:10px">', '1', '21'),
  (NULL, '<p type="font-size:10px">', '0', '21'),
  (NULL, '<p style=font-size:10px>', '0', '21'),
  (NULL, 'font-family: Verdana', '1', '22'),
  (NULL, 'font-size: Verdana', '0', '22'),
  (NULL, 'font: Verdana', '0', '22'),
  (NULL, 'background-color: red', '1', '23'),
  (NULL, 'background color: red', '0', '23'),
  (NULL, 'background: red', '0', '23'),
  (NULL, '<p align="right">', '1', '24'),
  (NULL, '<p margin="right">', '0', '24'),
  (NULL, '<p move="right">', '0', '24'),
  (NULL, 'Et dokumenti loogiliselt jaotada', '1', '25'),
  (NULL, 'Et tabelite vahele vahesid jätta', '0', '25'),
  (NULL, 'Paragrahvide asendamiseks', '0', '25'),
  (NULL, 'textarea tag', '1', '26'),
  (NULL, 'text tag', '0', '26'),
  (NULL, 'textml tag', '0', '26'),
  (NULL, 'rowspan',  '1', '27'),
  (NULL, 'rn', '0', '27'),
  (NULL, 'rownumb', '0', '27'),
  (NULL, '<ol>', '1', '28'),
  (NULL, '<ul>', '0', '28'),
  (NULL, '<ordlist>', '0', '28'),
  (NULL, '<ul>', '1', '29'),
  (NULL, '<ol>', '0', '29'),
  (NULL, '<unlist>', '0', '29'),
  (NULL, 'src', '1', '30'),
  (NULL, 'url', '0', '30'),
  (NULL, 'href', '0', '30'),
  (NULL, 'face', '1', '31'),
  (NULL, 'font', '0', '31'),
  (NULL, 'fontname', '0', '31'),
  (NULL, 'head tag-is', '1', '32'),
  (NULL, 'body tag-is', '0', '32'),
  (NULL, 'ükskõik kummas', '0', '32'),
  (NULL, '2', '1', '33'),
  (NULL, '3', '0', '33'),
  (NULL, '1', '0', '33'),
  (NULL, '_blank', '1', '34'),
  (NULL, '_newtab', '0', '34'),
  (NULL, 'blank', '0', '34'),
  (NULL, '<h7>', '1', '35'),
  (NULL, '<h4>', '0', '35'),
  (NULL, '<h2>', '0', '35');

INSERT INTO `practical` VALUES ('1', '1. Loo suurima formaadiga pealkiri, mille sisuks on vabalt valitud tekst. Määra pealkirja värvuseks sinine, fontiks Verdana ja suuruseks 35 pikslit.; 2. Loo paragrahv, mille sisuks on vabalt valitud tekst. Määra paragrahvi värvuseks punane, fontiks Arial ja suuruseks 40 pikslit.; 3. Loo tabel, kus on kaks rida ja kolm veergu. Esimese rea esimesse veergu kirjuta "Eesnimi", teise veergu "Vanus" ja kolmandasse veergu "Lemmik värv". Teise rea veergudesse kirjuta esimese rea veergudele vastavad väärtused.; 4. Määra tabelile ühe piksline must raam, joonda tekst keskele, kasuta fonti Calibri ja määra teksti suuruseks 40 pikslit. Tabeli laiuseks määra 70%.;');